Unirep/Unirep-Social

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.prettierignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE

https://github.com/Unirep/Unirep-Social/community

Update documents according to community standards

---

core/synchronizer.ts

-
-
-
Depends unirep/unirep#58

refactor: handle nullifier checks in base synchronizer

---

packages/frontend/jest.config.js
packages/frontend/package.json
packages/frontend/src/__tests__/feed.js
packages/frontend/src/__tests__/helpWidget.js
packages/frontend/src/__tests__/loadingButton.js
packages/frontend/src/__tests__/loadingCover.js
packages/frontend/src/__tests__/router.js

- This PR adds unit tests for the loadingButton, loadingCover, Feed, and AppRouter components. 
- Additional unit tests added and specified above.
- ```test-utils.tsx``` file was added to add a wrapper around all the tests because MobX requires a Provider around components that are using a store (this is still being worked on so you will see comments in this file for now).
- Reconfigured Jest to ignore any .ico files and added the "preset" option. 
- Added two more testing scripts for "watch" functionality and code coverage. Code coverage will be reconfigured when more tests are written.

Add: unit tests, test-utils file for MobX, and Jest reconfiguration

---

.circleci/config.yml
README.md
package.json

Remove need to manually call `yarn bootstrap` during install.

fix: bootstrap with install command

---

packages/frontend/src/__tests__/blockButton.js
packages/frontend/src/__tests__/commentBlock.js
packages/frontend/src/__tests__/signupPage.js

- Add minor improvements to a few unit tests.

Add: minor improvements for assertions

---

packages/frontend/src/__tests__/mainPage.js
packages/frontend/src/context/UI.ts
packages/frontend/src/context/User.ts
packages/frontend/src/layout/banner/banner.tsx

- store `hasBanner` in `UserContext` and in localStorage (cache)

feat: store `hasBanner` in webpage cache

---

.gitignore
packages/frontend/cypress.config.ts
packages/frontend/cypress/e2e/signup.cy.ts
packages/frontend/cypress/support/e2e.ts

fix(frontend): e2e test fixes

---

packages/frontend/src/__tests__/postBlock.js
packages/frontend/src/__tests__/textEditor.js

- Add unit test for the TextEditor.

Add(frontend): textEditor test

---

packages/frontend/src/__tests__/textEditor.js

- Previously the test did not fully simulate a user typing text into the textEditor and only changed the default `content`. Now, the test fully simulates a user typing into the textarea.

Minor fix to textEditor test

---

packages/frontend/src/__tests__/getStarted.js
packages/frontend/src/__tests__/onBoarded.js
packages/frontend/src/__tests__/signin.js
packages/frontend/src/__tests__/signup.js
packages/frontend/src/__tests__/startPage.js
packages/frontend/src/__tests__/textEditor.js
packages/frontend/src/pages/startPage/getStarted.tsx
packages/frontend/src/pages/startPage/onboarded.tsx
packages/frontend/src/pages/startPage/signin.tsx

- This PR adds unit tests for the signup flow and minor changes involving async tests.
- Secondarily, a few grammar changes were made.

Unit tests for signup flow

---

packages/frontend/src/components/commentBlock.tsx
packages/frontend/src/constants.ts
packages/frontend/src/utils.ts

- Etherscan link of comments should be `transactionHash`
-
-

fix(frontend): etherscan link of comments

---

packages/backend/src/constants.ts
packages/backend/src/routes/RecordRouter.ts
packages/backend/src/routes/VoteRouter.ts
packages/core/src/schema.ts
packages/core/src/synchronizer.ts
packages/frontend/src/__tests__/actionDetails.js
packages/frontend/src/__tests__/commentBlock.js
packages/frontend/src/__tests__/commentsList.js
packages/frontend/src/__tests__/postPage.js
packages/frontend/src/components/blockButton.tsx
packages/frontend/src/components/commentBlock.tsx
packages/frontend/src/components/postBlock.tsx
packages/frontend/src/constants.ts
packages/frontend/src/pages/userPage/activityWidget.tsx
packages/frontend/src/sass/components/_postBlock.scss
packages/frontend/src/utils.ts

fix: query records by nanoid

---

packages/backend/src/daemons/TransactionManager.ts

fix(backend): handle rate limiting

---

packages/frontend/cypress/e2e/login.cy.ts
packages/frontend/src/context/UI.ts
packages/frontend/src/layout/overlay/overlay.tsx
packages/frontend/src/layout/sideColumn/userInfoWidget.tsx
packages/frontend/src/pages/settingPage/privateKey.tsx
packages/frontend/src/pages/startPage/signin.tsx

- disable sign out button in the `overlay` 
- store `hasDownloadPrivateKey` in localStorage to prevent letting user download private key after reloading page
- if the user signin, automatically set `hasDownloadPrivateKey` to `true`

fix: bugs related to letting user downloading their private key

---

.circleci/config.yml
packages/frontend/.gitignore
packages/frontend/worker/index.js
packages/frontend/wrangler.toml

Automatically deploys the frontend to [social-staging.unirep.io](https://social-staging.unirep.io) when pull requests are merged to `main`.

feat: frontend staging deployment

---

packages/frontend/src/utils.ts

- fix date time display bug on `activityWidget` by remove redundant date time transform

fix: activity widget time display bug

---

packages/backend/src/constants.ts
packages/backend/src/routes/CommentRouter.ts
packages/backend/src/routes/PostRouter.ts
packages/backend/test/comment.test.ts
packages/backend/test/post.test.ts
packages/backend/test/utils.ts

- add delete post function and api
- add delete post test
-

feat: add delete post and comment and add tests

---

packages/frontend/src/__tests__/postBlock.js
packages/frontend/src/__tests__/refreshReminder.js
packages/frontend/src/components/postBlock.tsx
packages/frontend/src/components/refreshReminder.tsx
packages/frontend/src/components/writingField.tsx
packages/frontend/src/context/EpochManager.ts
packages/frontend/src/context/UI.ts
packages/frontend/src/context/User.ts
packages/frontend/src/layout/sideColumn/userInfoWidget.tsx
packages/frontend/src/pages/basicPage/basicPage.tsx

- add `waitForSync` before every proof generating
- put `latestTransitionedEpoch` to `observed`

fix: add waitForSync to avoid using wrong latestTransitionedEpoch

---

packages/frontend/src/components/voteBox.tsx
packages/frontend/src/sass/components/_voteBox.scss

fix: voteBox position

---

packages/backend/src/constants.ts
packages/backend/src/routes/CommentRouter.ts
packages/backend/src/routes/PostRouter.ts
packages/backend/test/comment.test.ts
packages/backend/test/post.test.ts
packages/backend/test/utils.ts
packages/core/src/schema.ts

- change `DELETED_CONTENT`
- add `TITLE_LABEL` to distinguish title from content in `hashedContent`
- label the posts if they were modified

Backend: edit and delete post related

---

packages/frontend/cypress/e2e/landing.cy.ts
packages/frontend/cypress/support/commands.ts
packages/frontend/src/__tests__/getStarted.js
packages/frontend/src/__tests__/startPage.js
packages/frontend/src/layout/banner/banner.tsx
packages/frontend/src/pages/startPage/getStarted.tsx
packages/frontend/src/pages/startPage/onboarded.tsx

- change to correct link on `join us`
- add `grab my private key` button on the last step of onboarding

Frontend: complete onboarding page

---

packages/frontend/src/__tests__/editPage.js

This PR is adding unit test coverage to the `<EditPage/>` component.

Edit post unit test

---

packages/frontend/src/layout/sideColumn/postsWidget.tsx

- post ranking is not according to boost amount before, but id. Fix it.
- If user is the author of the post only depends on `currentEpochKeys`, modified to `allEpks`

fix: post ranking display wrong

---

packages/backend/src/routes/CommentRouter.ts
packages/backend/src/routes/PostRouter.ts
packages/backend/src/routes/RecordRouter.ts
packages/core/src/synchronizer.ts
packages/frontend/src/components/refreshReminder.tsx
packages/frontend/src/constants.ts
packages/frontend/src/context/Post.ts
packages/frontend/src/context/Queue.ts
packages/frontend/src/context/UI.ts
packages/frontend/src/context/User.ts
packages/frontend/src/layout/progressBar/progressBar.tsx
packages/frontend/src/layout/sideColumn/userInfoWidget.tsx
packages/frontend/src/pages/userPage/activityWidget.tsx
packages/frontend/src/pages/userPage/userPage.tsx

- add `ActionType.EditPost`, `ActionType.DeletePost`, `ActionType.EditComment`, `ActionType.DeleteComment`, and `ActionType.Airdrop` in `core/src/synchronizer.ts`
- Modify the import in backend and frontend both from `@unirep-social/core`
- add `Record` after edit/delete post/comment
- change the `metadata` in queue data while `ActionType` is `EditPost`, `DeletePost`, `EditComment`, or `DeleteComment`

Add `ActionType`

---

packages/backend/package.json
packages/backend/yarn.lock
packages/circuits/package.json
packages/circuits/yarn.lock
packages/core/package.json
packages/core/test/Username.test.ts
packages/core/yarn.lock
packages/frontend/package.json

`@unirep/core` v1.0.4

---

packages/backend/src/routes/AirdropRouter.ts
packages/backend/src/routes/CommentRouter.ts
packages/backend/src/routes/PostRouter.ts
packages/backend/test/airdrop.test.ts
packages/backend/test/subsidy.test.ts
packages/backend/test/utils.ts

Subsidy check

---

packages/frontend/src/context/Post.ts

If I choose `epkNonce != 0` to post, the computed epoch is float when I edited.
- we should use `Math.floor()` to get the integer
-
-

fix(frontend): fix epoch being float

---

packages/circuits/circuits/proveGraffitiPreimage.circom
packages/circuits/circuits/test/proveGraffitiPreimage_test.circom
packages/circuits/scripts/circuits.mjs
packages/circuits/test/proveGraffitiPreimage.test.ts

[circuit] proves an epoch key and graffiti pre-image only

---

packages/frontend/src/pages/settingPage/privateKey.tsx

chore: lint

---

.circleci/config.yml

fix: staging deploy script

---

packages/frontend/src/context/Post.ts
packages/frontend/src/context/User.ts

chore(frontend): remove unneccessary loading

---

packages/frontend/src/sass/pages/_user.scss

fix(frontend): fix activity ui

---

packages/backend/src/Synchronizer.ts
packages/backend/src/app.ts
packages/backend/src/routes/ConfigRouter.ts
packages/backend/src/routes/EpochRouter.ts
packages/backend/src/schema.ts
packages/frontend/src/config.ts
packages/frontend/src/context/Unirep.ts
packages/frontend/src/context/User.ts
packages/frontend/src/sass/pages/_user.scss

Fetch config from relay

---

packages/frontend/src/context/Post.ts
packages/frontend/src/context/User.ts

Reverts Unirep/Unirep-Social#212

Revert "chore(frontend): remove unneccessary loading"

---

packages/frontend/package.json
packages/frontend/src/components/commentBlock.tsx
packages/frontend/src/components/postBlock.tsx
packages/frontend/src/components/textEditor.tsx
packages/frontend/src/pages/userPage/activityWidget.tsx
packages/frontend/src/utils.ts
yarn.lock

feat(frontend): add latex markdown support

---

.circleci/config.yml
README.md
package.json

fix: update readme, add `lint:fix` script

---

packages/frontend/src/context/User.ts

fix(frontend): fix loading epoch
